//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyMark.OnBase.UnityAPI.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeyMark.OnBase.UnityAPI.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Authentication_Category {
            get {
                return ResourceManager.GetString("Authentication_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set, continue executing the remaining activities even if the current activity has failed..
        /// </summary>
        public static string ContinueOnError_Description {
            get {
                return ResourceManager.GetString("ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContinueOnError.
        /// </summary>
        public static string ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return a DataTable list of LifeCycles in OnBase.
        /// </summary>
        public static string GetLifeCycles_Description {
            get {
                return ResourceManager.GetString("GetLifeCycles_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get LifeCycles.
        /// </summary>
        public static string GetLifeCycles_DisplayName {
            get {
                return ResourceManager.GetString("GetLifeCycles_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataTable of LifeCycles.
        /// </summary>
        public static string GetLifeCycles_LifeCycles_Description {
            get {
                return ResourceManager.GetString("GetLifeCycles_LifeCycles_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LifeCycles.
        /// </summary>
        public static string GetLifeCycles_LifeCycles_DisplayName {
            get {
                return ResourceManager.GetString("GetLifeCycles_LifeCycles_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input_Category {
            get {
                return ResourceManager.GetString("Input_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options_Category {
            get {
                return ResourceManager.GetString("Options_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output_Category {
            get {
                return ResourceManager.GetString("Output_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string Server_Category {
            get {
                return ResourceManager.GetString("Server_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session.
        /// </summary>
        public static string Session_Category {
            get {
                return ResourceManager.GetString("Session_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the amount of time (in milliseconds) to wait for the activity to run before an error is thrown. The default value is 60000 (1 minute)..
        /// </summary>
        public static string Timeout_Description {
            get {
                return ResourceManager.GetString("Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (milliseconds).
        /// </summary>
        public static string Timeout_DisplayName {
            get {
                return ResourceManager.GetString("Timeout_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity timed out and was canceled..
        /// </summary>
        public static string Timeout_Error {
            get {
                return ResourceManager.GetString("Timeout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Server Datasource Name.
        /// </summary>
        public static string UseOnBaseUnity_AppServerDsn_Description {
            get {
                return ResourceManager.GetString("UseOnBaseUnity_AppServerDsn_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppServerDsn.
        /// </summary>
        public static string UseOnBaseUnity_AppServerDsn_DisplayName {
            get {
                return ResourceManager.GetString("UseOnBaseUnity_AppServerDsn_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Service URL.
        /// </summary>
        public static string UseOnBaseUnity_AppServerUrl_Description {
            get {
                return ResourceManager.GetString("UseOnBaseUnity_AppServerUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppServerUrl.
        /// </summary>
        public static string UseOnBaseUnity_AppServerUrl_DisplayName {
            get {
                return ResourceManager.GetString("UseOnBaseUnity_AppServerUrl_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Session Connected / Is Session Connected.
        /// </summary>
        public static string UseOnBaseUnity_Connected_Description {
            get {
                return ResourceManager.GetString("UseOnBaseUnity_Connected_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string UseOnBaseUnity_Connected_DisplayName {
            get {
                return ResourceManager.GetString("UseOnBaseUnity_Connected_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open or Use a connection to OnBase Unity API Server.
        /// </summary>
        public static string UseOnBaseUnity_Description {
            get {
                return ResourceManager.GetString("UseOnBaseUnity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use OnBase Unity.
        /// </summary>
        public static string UseOnBaseUnity_DisplayName {
            get {
                return ResourceManager.GetString("UseOnBaseUnity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default, Enterprise Core or Query Metering.
        /// </summary>
        public static string UseOnBaseUnity_LicenseType_Description {
            get {
                return ResourceManager.GetString("UseOnBaseUnity_LicenseType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LicenseType.
        /// </summary>
        public static string UseOnBaseUnity_LicenseType_DisplayName {
            get {
                return ResourceManager.GetString("UseOnBaseUnity_LicenseType_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Messages.
        /// </summary>
        public static string UseOnBaseUnity_Message_Description {
            get {
                return ResourceManager.GetString("UseOnBaseUnity_Message_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string UseOnBaseUnity_Message_DisplayName {
            get {
                return ResourceManager.GetString("UseOnBaseUnity_Message_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnBase User Password or blank for current user.
        /// </summary>
        public static string UseOnBaseUnity_Password_Description {
            get {
                return ResourceManager.GetString("UseOnBaseUnity_Password_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string UseOnBaseUnity_Password_DisplayName {
            get {
                return ResourceManager.GetString("UseOnBaseUnity_Password_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Service Session ID.
        /// </summary>
        public static string UseOnBaseUnity_SessionID_Description {
            get {
                return ResourceManager.GetString("UseOnBaseUnity_SessionID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SessionID.
        /// </summary>
        public static string UseOnBaseUnity_SessionID_DisplayName {
            get {
                return ResourceManager.GetString("UseOnBaseUnity_SessionID_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnBase User ID or blank for current user.
        /// </summary>
        public static string UseOnBaseUnity_Username_Description {
            get {
                return ResourceManager.GetString("UseOnBaseUnity_Username_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UseOnBaseUnity_Username_DisplayName {
            get {
                return ResourceManager.GetString("UseOnBaseUnity_Username_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value either for {0} or {1}, but not both..
        /// </summary>
        public static string ValidationExclusiveProperties_Error {
            get {
                return ResourceManager.GetString("ValidationExclusiveProperties_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide values for both {0} and {1}..
        /// </summary>
        public static string ValidationOverloadGroup_Error {
            get {
                return ResourceManager.GetString("ValidationOverloadGroup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be used outside of a {0}..
        /// </summary>
        public static string ValidationScope_Error {
            get {
                return ResourceManager.GetString("ValidationScope_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for {0}..
        /// </summary>
        public static string ValidationValue_Error {
            get {
                return ResourceManager.GetString("ValidationValue_Error", resourceCulture);
            }
        }
    }
}
